### PR TITLE
Implement JWT checks locally

### PR DESCRIPTION
**Pull request by omsmith**
* Remove (production) dependency on jsonwebtoken
* Add clock skew allowance (semver-minor)
* Re-introduce "nbf" checks (won't break everything due to lack of clock skew allowance)

Questions:
- [x] Default clock skew - 300s okay (believe this is the .NET default we're using)?
- [x] Are we okay with validating claims before verifying them?

TODO:
- [x] Test the default clock skew timing
- [x] Minor tweaks

### CODE REVIEW

**Comment by omsmith** [comment]
@j3parker the 300s seem legit?

**Comment by omsmith** [comment]
@j3parker to make things easier, I've opted to validate claims prior to actually verifying the signature. Do you see a problem with that? It differs from previous behavior, and I think, perhaps, behaviour of the .NET library, but it also saves compute.

**Comment by j3parker** [comment]
300 sounds fine to me... I don't remember what we do in .NET... the number "2 minutes" is in my head but I remember we got surprised by some behavior in the .NET JWT libraries so I can't remember (probably something I should know...)

I can't see any problem with that. Definitely commutative (other than error msg/perf) and seems unlikely to make refactors more risky.

**Comment by omsmith** [comment]
https://github.com/AzureAD/azure-activedirectory-identitymodel-extensions-for-dotnet/blob/e6d903b4f8d3c6d7697dc70cd54ae905b18b65fe/src/System.IdentityModel.Tokens.Jwt/TokenValidationParameters.cs#L86

**Comment by j3parker** [comment]
That's the ticket... thanks!

**Pull request merged**
